In [ ]:
NumPy basics(Array creation)

In [1]:
import numpy as np

#1D array 
arr1 = np.array([1,3,5,7,9])
print(arr1)

#2D array
arr2 = np.array([[1,2],[3,4],[5,6]])
print(arr2)

#special arrays
zeros = np.zeros((3,4)) #3 rows, 4 columns 2*3 zeros
ones = np.ones((2,3)) #2 rows, 3 columns 2*3 ones
rand = np.random.rand(2,3) #2 rows, 3 columns 2*3 random values between 0 and 1

print("Zeros:\n", zeros)
print("Ones:\n", ones)      
print("Random:\n", rand)

[1 3 5 7 9]
[[1 2]
 [3 4]
 [5 6]]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Random:
 [[0.30156067 0.14091176 0.54545484]
 [0.43467967 0.18753292 0.41538335]]
