NumPy: (array basics) Slicing and Indexing 

In [5]:
import numpy as np

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1])    # element at row0, col1
print(mat[:,1])    # entire 2nd column
print(mat[1,:])    # entire 2nd row


2
[2 5 8]
[4 5 6]


In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])      # first element
print(arr[-1])     # last element
print(arr[1:4])    # slicing [start:end]


10
50
[20 30 40]


Useful fn

In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(np.sum(arr))       # sum of elements
print(np.mean(arr))      # mean
print(np.std(arr))       # standard deviation
print(np.max(arr))       # max
print(np.min(arr))       # min
print(np.argmin(arr))    # index of min
print(np.argmax(arr))    # index of max


15
3.0
1.4142135623730951
5
1
0
4
