# Vector and it's operations

In [4]:
import numpy as np

a = np.array([2,3,4])
b = np.array([5,4,3])

print("Addition:", a + b)
print("Scalar multiplication", 3 * a)
print("Dot Product:", np.dot(a,b))

Addition: [7 7 7]
Scalar multiplication [ 6  9 12]
Dot Product: 34


# Matrix opertaions

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

print("Addition:\n", A + B)
print("Scalar Multiplication:\n", 2 * A)
print("Matrix Multiplication:\n", np.dot(A, B))
print("Transpose:\n", A.T)

Addition:
 [[3 2]
 [4 7]]
Scalar Multiplication:
 [[2 4]
 [6 8]]
Matrix Multiplication:
 [[ 4  6]
 [10 12]]
Transpose:
 [[1 3]
 [2 4]]
