# Vector and it's operations

In [9]:
import numpy as np

a = np.array([2,3,4])
b = np.array([5,4,3])

print("Addition:", a + b)
print("Scalar multiplication", 3 * a)
print("Dot Product:", np.dot(a,b))

Addition: [7 7 7]
Scalar multiplication [ 6  9 12]
Dot Product: 34


# Matrix opertaions

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

print("Addition:\n", A + B)
print("Scalar Multiplication:\n", 2 * A)
print("Matrix Multiplication:\n", np.dot(A, B))
print("Transpose:\n", A.T)

Addition:
 [[3 2]
 [4 7]]
Scalar Multiplication:
 [[2 4]
 [6 8]]
Matrix Multiplication:
 [[ 4  6]
 [10 12]]
Transpose:
 [[1 3]
 [2 4]]


# Special matrix

In [11]:
A = np.array([[1, 2], [3, 4]])
print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))

Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# Grayscale Conversion
( Grayscale Image = 2D matrix of pixel intensities (0–255).
RGB Image = 3D matrix (Height × Width × 3). )

We convert RGB → Gray using a weighted sum (because human eyes see green > red > blue).

In [12]:
pixel = np.array([100, 150, 200]) #R, G, B
gray = 0.2989*pixel[0] + 0.5870*pixel[1] + 0.114*pixel[2]
print("Gray Value:", gray)

Gray Value: 140.74
